### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/batimagen#1]
### Primer barrido de librerías

**Recomendadas por Kr0n0**
- [exiftool](https://www.npmjs.com/package/exiftool) *A node.js wrapper around exiftool, a commandline utility that can extract metadata from many different filetypes, including JPEG, PNG, PDF, WMV, MOV. For a full list see the exiftool list of supported filetypes.*

**Node Jsdom Scrape Google's Reverse Image Search**
>"I want to programatically find a list of URLs for similar images given an image URL. I can't find any free image search APIs so I'm trying to do this by scraping Google's Search by Image...."
- [StackOverflow Resource](https://stackoverflow.com/questions/13972240/node-jsdom-scrape-googles-reverse-image-search)

**Stegdetect**:
Librería para detectar contenido esteganográfico: La esteganografía (del griego στεγανος steganos, "cubierto" u "oculto", y γραφος graphos, "escritura") trata el estudio y aplicación de técnicas que permiten ocultar mensajes u objetos, dentro de otros, llamados portadores, de modo que no se perciba su existencia [Wikipedia](https://es.wikipedia.org/wiki/Esteganograf%C3%ADa).
- [stegdetect](https://github.com/abeluck/stegdetect/)

**Comment by ElenaMLopez** [comment]
Creo que estos son los tres recursos que nos han pasado. Si conocéis más añadirlos! ^.^

**Comment by UlisesGascon** [comment]
Usamos [Google Cloud Vision](https://cloud.google.com/vision/?hl=es)?
