### ISSUE TITLE
view index

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/batimagen#14]
### Pendiente
- [x] Hacer algo con el "logo"
- [x] Pasar todo a ingles
- [x] Arreglar los estilos del formulario
- [x] Botones de _"efecto hacker"_
- [x] Espacio para el disclaimer
- [x] Espacio para la licencia
- [x] Link + ¿texto? sobre OSW Guilds
- [x] Link a Github

**Comment by ElenaMLopez** [comment]
- [ ] Poner cros en el pointer para hover en inputs y boton
- [ ] Poner estilos al upload
- [ ] Agregar licencia gpl3
- [ ] Traducir disclaimer.
