### ISSUE TITLE
Dockerizar la app

### ISSUE THREAD

**Issue by ElenaMLopez** [OSWeekends/batimagen#25]
Como **desarrollador** deseo dockerizar la app.

#### Recursos:
    - https://semaphoreci.com/community/tutorials/dockerizing-a-node-js-web-application

**Comment by UlisesGascon** [comment]
```docker
FROM node:11

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY scripts/*.sh ./scripts/
RUN npm run install-dependencies

COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]
````

**Comment by Kr0n0** [comment]
Tres recomendaciones :

- Crear un .dockerignore con el siguiente contenido : 

```
node_modules
npm-debug.log
```

- Gestionar en el Dockerfile el control de versiones con variables tipo :
```
LABEL osw.version.release.number="1.0"
LABEL osw.version.release.date="YYMMDD"
MAINTAINER usuario@dominio.com
```
De esta manera luego si se integra en un sistema CI podéis controlar con estas variables el versionado de manera sencilla.

- Integrar el soporte travis CI con el docker dºe node y los tests :
https://codeburst.io/ci-cd-with-github-travis-ci-and-heroku-e088a24f32ef

**Comment by UlisesGascon** [comment]
ya esta completado!
