### ISSUE TITLE
Fix for version 1.0.1

### ISSUE THREAD

**Issue by ElenaMLopez** [OSWeekends/batimagen#39]
- [x] - Actualizar el repalce de textos
- [x] - Probar el replace con varios ficheros con muchos espacios
- [x] - Subir el package a la version 1.0.1
- [x] - Cerrar definitivamente la docu
- [x] - Ver que funcionan bien los cambios en los botones de forensica
- [x] - Verificar que el PR de Fran del config.js no se ha propagado (no hacia falta cambiar nada en el config.js)
- [x] - Hacer un PR de dev a Master

**Comment by UlisesGascon** [comment]
All done! Awesome work team! 👍
