### ISSUE TITLE
Corrección ortográfica README

### ISSUE THREAD

**Issue by sergitxu** [OSWeekends/batimagen#55]
Hay varias falta de ortografía en el archivo README, me gustaría solucionarlo.

**Comment by UlisesGascon** [comment]
Dale caña ^^

¿Nos mandas un PR?

**Comment by sergitxu** [comment]
¿Hago rama o a master?

**Comment by UlisesGascon** [comment]
Tira directamente con `development` ;-)

**Comment by UlisesGascon** [comment]
😓 cerré acidentalmente el issue.

**Comment by sergitxu** [comment]
Me da 403, ¿necesito permiso para pushear a dev? :sweat_smile:

**Comment by UlisesGascon** [comment]
Necesitarias hacer el PR desde un Fork, [te dejo una mini-guia](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) :-)

**Comment by sergitxu** [comment]
¡Gracias!
